### ISSUE TITLE
Diagram captions are not visible in dark theme

### ISSUE THREAD

**Issue by cjchacon** [MicrosoftDocs/architecture-center.es-es#39]
You can see in the link below that the image is not adapted to the dark theme.
https://i.imgur.com/6grMba8.png

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b8865190-b9ac-ae5e-2590-30237ed43697
* Version Independent ID: 45d8bb8c-10f1-de72-6644-a20ba60a32af
* Content: [Diseño de una canalización de CI/CD con Azure DevOps - Azure Example Scenarios](https://docs.microsoft.com/es-es/azure/architecture/example-scenario/apps/devops-dotnet-webapp#feedback)
* Content Source: [docs/example-scenario/apps/devops-dotnet-webapp.md](https://github.com/microsoftdocs/architecture-center.es-es/blob/live/docs/example-scenario/apps/devops-dotnet-webapp.md)
* Service: **architecture-center**
* Sub-service: **example-scenario**
* GitHub Login: @christianreddington
* Microsoft Alias: **pnp**

**Comment by srvbpigh** [comment]
Hello, @cjchacon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @cjchacon ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/architecture-center/issues/1653

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
